[package]
name = "vertex-cover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6"
rs-graph = "0.20"
ordered-float = "3.4"

[dev-dependencies]
petgraph-gen = "0.1.3"
rand = "0.8"
